version: '3.9'
services:
  course-service:
    build: ./course-service
    ports:
      - 5001:8080
    volumes:
      - ./course-service:/usr/app/src
  website:
    image: nginx:alpine
    volumes:
      - ./website:/usr/share/nginx/html
    ports:
      - 5002:80
    depends_on:
      - course-service







